# Generated by Django 4.2.7 on 2023-12-16 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leave_type', '0001_initial'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('LeaveID', models.IntegerField(primary_key=True, serialize=False)),
                ('LeaveStartDate', models.DateTimeField()),
                ('LeaveEndDate', models.DateTimeField()),
                ('Reason', models.CharField(max_length=500)),
                ('LeaveStatus', models.CharField(max_length=255)),
                ('EmpID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
                ('LeaveTypeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave_type.leavetype')),
            ],
        ),
    ]
