# Generated by Django 4.2.7 on 2024-01-02 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_alter_leave_leaveid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='LeaveEndDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='leave',
            name='LeaveStartDate',
            field=models.DateField(),
        ),
    ]
