# Generated by Django 4.2.7 on 2024-01-03 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave_type', '0003_leavetype_leavetypedescription_and_more'),
        ('base', '0009_employee_bank_employee_bankaccountnumer_and_more'),
        ('leave', '0004_alter_leave_leavestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('LeaveRequestID', models.AutoField(primary_key=True, serialize=False)),
                ('LeaveStartDate', models.DateField()),
                ('LeaveEndDate', models.DateField()),
                ('Reason', models.CharField(max_length=500)),
                ('LeaveStatus', models.CharField(default=True, max_length=255)),
                ('EmpID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
                ('LeaveTypeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave_type.leavetype')),
            ],
        ),
        migrations.DeleteModel(
            name='Leave',
        ),
    ]
