# Generated by Django 4.2.7 on 2024-01-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_leaverequest_delete_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='Duration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
