# Generated by Django 4.2.7 on 2024-01-31 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_leaverequest_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='LeaveStatus',
            field=models.CharField(choices=[('Chờ xác nhận', 'Chờ xác nhận'), ('Chờ phê duyệt', 'Chờ phê duyệt'), ('Đã phê duyệt', 'Đã phê duyệt'), ('Bị từ chối', 'Bị từ chối')], default='Chờ xác nhận', max_length=255),
        ),
    ]
