# Generated by Django 4.2.7 on 2024-02-21 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0007_alter_leaverequest_leavestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='LeaveStatus',
            field=models.CharField(choices=[('Chờ xác nhận', 'Chờ xác nhận'), ('Chờ phê duyệt', 'Chờ phê duyệt'), ('Đã phê duyệt', 'Đã phê duyệt'), ('Đã từ chối', 'Đã từ chối')], default='Chờ xác nhận', max_length=255),
        ),
    ]
