# Generated by Django 4.2.7 on 2023-12-07 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_a'),
    ]

    operations = [
        migrations.DeleteModel(
            name='a',
        ),
    ]
