# Generated by Django 4.2.7 on 2023-12-16 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('TimeID', models.IntegerField(primary_key=True, serialize=False)),
                ('TimeIn', models.DateTimeField()),
                ('TimeOut', models.DateTimeField()),
                ('EmpID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
            ],
        ),
    ]
