# Generated by Django 4.2.7 on 2024-01-04 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0003_timesheet_checkedin_alter_timesheet_timein_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='CheckedIn',
        ),
    ]
