# Generated by Django 4.2.7 on 2024-01-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0008_remove_timesheet_timestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='TimeStatus',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
