# Generated by Django 4.2.7 on 2024-02-28 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0009_timesheet_timestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='serial_number',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
