# Generated by Django 4.2.7 on 2024-02-28 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0010_timesheet_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='serial_number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
