# Generated by Django 4.2.7 on 2023-12-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('LeaveTypeID', models.IntegerField(primary_key=True, serialize=False)),
                ('LeaveTypeName', models.CharField(max_length=255)),
                ('Subsidize', models.FloatField()),
            ],
        ),
    ]
