# Generated by Django 4.2.7 on 2024-01-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_type', '0002_alter_leavetype_leavetypeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='LeaveTypeDescription',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leavetype',
            name='LimitedDuration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
