# Generated by Django 4.2.7 on 2024-01-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('RoleID', models.AutoField(primary_key=True, serialize=False)),
                ('RoleName', models.CharField(max_length=200)),
            ],
        ),
    ]
