# Generated by Django 4.2.7 on 2023-12-13 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('DepID', models.AutoField(primary_key=True, serialize=False)),
                ('DepName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmpID', models.AutoField(primary_key=True, serialize=False)),
                ('EmpName', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=15)),
                ('HireDate', models.DateTimeField()),
                ('BirthDate', models.DateTimeField()),
                ('Address', models.CharField(max_length=255)),
                ('PhotoPath', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
                ('Salary', models.FloatField()),
                ('role', models.BooleanField()),
                ('EmpStatus', models.BooleanField()),
                ('DepID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.department')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('LeaveTypeID', models.AutoField(primary_key=True, serialize=False)),
                ('LeaveTypeName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('PosID', models.AutoField(primary_key=True, serialize=False)),
                ('PosName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('proj_id', models.AutoField(primary_key=True, serialize=False)),
                ('proj_name', models.CharField(max_length=20)),
                ('proj_value', models.IntegerField()),
                ('date_start', models.DateField(auto_now=True)),
                ('date_end', models.DateField()),
                ('proj_description', models.CharField(max_length=200)),
                ('complete', models.CharField(choices=[('finished', 'Finished'), ('unfinished', 'Unfinished')], default='unfinished', max_length=20)),
                ('manager_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('TimeID', models.AutoField(primary_key=True, serialize=False)),
                ('TimeIn', models.DateTimeField()),
                ('TimeOut', models.DateTimeField()),
                ('EmpID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('proj_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.project')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('LeaveID', models.AutoField(primary_key=True, serialize=False)),
                ('LeaveStartDate', models.DateTimeField()),
                ('LeaveEndDate', models.DateTimeField()),
                ('Reason', models.CharField(max_length=500)),
                ('LeaveStatus', models.CharField(max_length=255)),
                ('EmpID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
                ('LeaveTypeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.leavetype')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='PosID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.position'),
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('UserID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('EmpID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
