# Generated by Django 4.2.7 on 2023-11-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='check_in_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_out_time',
            field=models.DateTimeField(),
        ),
    ]
