# Generated by Django 4.2.7 on 2023-12-13 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_a'),
    ]

    operations = [
        migrations.DeleteModel(
            name='a',
        ),
    ]
