# Generated by Django 4.2.7 on 2023-11-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_useraccount_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='date_of_hire',
            field=models.DateField(auto_now=True),
        ),
    ]
