# Generated by Django 4.2.7 on 2023-12-13 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_delete_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='password',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='EmpID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.employee'),
        ),
    ]
