# Generated by Django 4.2.7 on 2023-12-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_employee_address_alter_employee_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='EmpID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
