# Generated by Django 4.2.7 on 2023-12-19 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_employee_empid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='UserStatus',
            field=models.BooleanField(default=True),
        ),
    ]
