# Generated by Django 4.2.7 on 2023-12-14 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_useraccount_groups_useraccount_is_superuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('JobID', models.AutoField(primary_key=True, serialize=False)),
                ('JobName', models.CharField(max_length=255)),
                ('JobChangeHour', models.FloatField()),
                ('DepID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.department')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryHistory',
            fields=[
                ('SalID', models.AutoField(primary_key=True, serialize=False)),
                ('SalFrom', models.DateTimeField()),
                ('SalEnd', models.DateTimeField()),
                ('SalAmount', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='PosID',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
        migrations.AddField(
            model_name='leavetype',
            name='Subsidize',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='DepID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.department'),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.AddField(
            model_name='salaryhistory',
            name='EmpID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='JobID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.job'),
        ),
    ]
