# Generated by Django 4.2.7 on 2023-12-19 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_job_jobid'),
        ('department', '0003_alter_department_empid'),
        ('base', '0006_alter_useraccount_userstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='DepID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='department.department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='JobID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='job.job'),
            preserve_default=False,
        ),
    ]
