# Generated by Django 4.2.7 on 2023-12-30 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_employee_depid_alter_employee_jobid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='EmpID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.employee'),
        ),
    ]
