# Generated by Django 4.2.7 on 2023-11-28 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='name',
        ),
    ]
