# Generated by Django 4.2.7 on 2023-12-04 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_delete_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='check_out_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
