# Generated by Django 4.2.7 on 2023-12-14 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_salaryhistory_salid_alter_salaryhistory_empid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='EmpID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='base.employee'),
            preserve_default=False,
        ),
    ]
