# Generated by Django 4.2.7 on 2024-01-06 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_employee_bank_employee_bankaccountnumer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Bank',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='BankAccountNumer',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='BankBranch',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Gender',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='TaxCode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
