# Generated by Django 4.2.7 on 2023-12-14 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_salaryhistory_empid'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='salaryhistory',
            constraint=models.UniqueConstraint(fields=('EmpID', 'SalFrom'), name='unique_salary_history'),
        ),
    ]
