# Generated by Django 4.2.7 on 2024-01-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_useraccount_empid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
