# Generated by Django 4.2.7 on 2023-12-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_salaryhistory_unique_salary_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='DepID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='EmpID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='JobID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leave',
            name='LeaveID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='LeaveTypeID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='TimeID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
