# Generated by Django 4.2.7 on 2024-01-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='CCCD',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
