# Generated by Django 4.2.7 on 2023-12-05 09:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_project_task_projectmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='complete',
            field=models.CharField(choices=[('finished', 'Finished'), ('unfinished', 'Unfinished')], default='unfinished', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='emp_id',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
