# Generated by Django 4.2.7 on 2023-12-05 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_project_complete_project_emp_id_delete_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='emp_id',
            new_name='useraccount',
        ),
    ]
