# Generated by Django 4.2.7 on 2024-01-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_employee_cccd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='BirthDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='HireDate',
            field=models.DateField(null=True),
        ),
    ]
