# Generated by Django 4.2.7 on 2023-12-14 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_salaryhistory_unique_salary_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryhistory',
            name='SalEnd',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='salaryhistory',
            name='SalFrom',
            field=models.DateField(primary_key=True, serialize=False),
        ),
    ]
