# Generated by Django 4.2.7 on 2024-01-07 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0013_department_manageid'),
        ('job', '0006_remove_job_jobchangehour_job_descriptions_and_more'),
        ('base', '0014_alter_employee_birthdate_alter_employee_hiredate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='DepID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='JobID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.job'),
        ),
    ]
