# Generated by Django 4.2.7 on 2023-12-14 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_salaryhistory_salend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryhistory',
            name='EmpID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employee'),
        ),
    ]
