# Generated by Django 4.2.7 on 2024-01-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_employee_photopath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='EmpStatus',
            field=models.CharField(default='Hoạt động', max_length=200),
        ),
    ]
