# Generated by Django 4.2.7 on 2023-12-16 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_salaryhistory_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salaryhistory',
            unique_together={('EmpID', 'SalFrom')},
        ),
    ]
