# Generated by Django 4.2.7 on 2023-12-19 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('job', '0002_alter_job_depid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='DepID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='department.department'),
        ),
    ]
