# Generated by Django 4.2.7 on 2023-12-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_job_depid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='JobID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
