# Generated by Django 4.2.7 on 2023-12-19 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_alter_department_empid'),
        ('job', '0004_alter_job_jobid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='DepID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='department.department'),
            preserve_default=False,
        ),
    ]
