# Generated by Django 4.2.7 on 2024-01-19 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_remove_job_jobchangehour_job_descriptions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Descriptions',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
