# Generated by Django 4.2.7 on 2023-12-19 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_employee_depid_alter_employee_jobid'),
        ('department', '0005_remove_department_empid'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='EmpID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.employee'),
            preserve_default=False,
        ),
    ]
