# Generated by Django 4.2.7 on 2024-01-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0011_remove_department_empid'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='DepShortName',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
