# Generated by Django 4.2.7 on 2024-01-03 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_employee_bank_employee_bankaccountnumer_and_more'),
        ('department', '0012_department_depshortname'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='ManageID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.employee'),
        ),
    ]
